language: node_js
node_js:
  - 10
cache: yarn
install:
  - yarn
before_script:
  - >-
    ([ -f "$(git rev-parse --git-dir)"/shallow ] && git fetch --unshallow) ||
    true
  - 'yarn commitlint --from="$TRAVIS_BRANCH" --to="$TRAVIS_COMMIT"'
  - 'yarn commitlint --from="$TRAVIS_COMMIT"'
script:
  - yarn test
  - yarn cypress run --record --key 2bebfc25-8487-4bf0-a6c8-4cfe5f64cc72
